# Generated by Django 4.1.7 on 2023-03-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvparser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tvparser',
            name='prise',
        ),
        migrations.AddField(
            model_name='tvparser',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
