# Generated by Django 4.1.7 on 2023-03-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_tvparser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvparser',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
