# Generated by Django 4.1.7 on 2023-03-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_tvparser_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvparser',
            name='description',
        ),
    ]
