# Generated by Django 4.1.7 on 2023-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyshow',
            name='prise',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена билета'),
        ),
    ]
