# Generated by Django 4.1.7 on 2023-02-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0002_tyshow_prise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TYshow',
            new_name='TVshow',
        ),
    ]
