# Generated by Django 4.1.7 on 2023-02-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='prise',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Колтчество'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название книги'),
        ),
    ]
